import { Order, UserRole, WeekRange } from './types';
import { totalAreaCm2, totalPieces } from './nestingService';

interface BuildOptions {
  orders: Order[];
  week: WeekRange;
  managerName: string;
}

interface WorkerGroup {
  userId: string;
  name: string;
  role: UserRole;
  orders: Order[];
}

/**
 * Builds a print-ready HTML document of the Manager Triage view
 * (weekly orders grouped by worker, with status, plates, and execution files).
 * Consumed by expo-print to generate a shareable PDF.
 */
export function buildManagerReportHtml({
  orders,
  week,
  managerName,
}: BuildOptions): string {
  const generatedAt = new Date();

  // Aggregate stats
  const pending = orders.filter((o) => o.status === 'pending').length;
  const done = orders.filter((o) => o.status === 'done').length;
  const totalPlates = orders.reduce(
    (s, o) => s + (o.actualSheets ?? o.estimatedSheets ?? 0),
    0,
  );
  const totalFiles = orders.reduce(
    (s, o) => s + (o.executionFiles?.length ?? 0),
    0,
  );
  const totalPiecesAll = orders.reduce((s, o) => s + totalPieces(o.shapes), 0);

  // Group by worker, sort by pending desc then name
  const map = new Map<string, WorkerGroup>();
  orders.forEach((o) => {
    if (!map.has(o.userId)) {
      map.set(o.userId, {
        userId: o.userId,
        name: o.userName,
        role: o.userRole,
        orders: [],
      });
    }
    map.get(o.userId)!.orders.push(o);
  });
  const groups = Array.from(map.values())
    .map((g) => ({
      ...g,
      orders: g.orders.slice().sort((a, b) => a.createdAt - b.createdAt),
    }))
    .sort((a, b) => {
      const ap = a.orders.filter((o) => o.status === 'pending').length;
      const bp = b.orders.filter((o) => o.status === 'pending').length;
      if (ap !== bp) return bp - ap;
      return a.name.localeCompare(b.name);
    });

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>Sherisha Workshop · Manager Triage Report</title>
<style>${baseStyles}</style>
</head>
<body>
  <div class="brand-bar">
    <div>
      <div class="brand-mark">Sherisha Workshop</div>
      <div class="brand-title">Manager Triage Report</div>
      <div class="brand-subtitle">Cycle: ${esc(week.label)} · ${esc(week.key)}</div>
    </div>
    <div class="brand-badge">Friday → Thursday</div>
  </div>

  <div class="stats-grid">
    <div class="stat-card warning">
      <div class="stat-label">In Queue</div>
      <div class="stat-value">${pending}</div>
    </div>
    <div class="stat-card success">
      <div class="stat-label">Completed</div>
      <div class="stat-value">${done}</div>
    </div>
    <div class="stat-card accent">
      <div class="stat-label">Total Plates</div>
      <div class="stat-value">${totalPlates}<span class="stat-unit">sheets</span></div>
    </div>
    <div class="stat-card">
      <div class="stat-label">Workers Active</div>
      <div class="stat-value">${groups.length}</div>
    </div>
  </div>

  <div class="meta-row">
    <strong>${totalPiecesAll}</strong> pieces produced this cycle
    · <strong>${orders.length}</strong> orders submitted
    · <strong>${totalFiles}</strong> execution file${totalFiles === 1 ? '' : 's'} attached
  </div>

  ${
    groups.length === 0
      ? `<div class="empty-state">
          <div class="empty-title">No orders this cycle</div>
          <div class="empty-sub">The triage queue is empty for ${esc(week.label)}.</div>
        </div>`
      : groups.map(renderWorker).join('')
  }

  <footer>
    Generated by ${esc(managerName)} · ${esc(formatDateTime(generatedAt.getTime()))}
    <br/>
    <span class="footer-brand">Sherisha Workshop Management · Internal use only</span>
  </footer>
</body>
</html>`;
}

function renderWorker(g: WorkerGroup): string {
  const pending = g.orders.filter((o) => o.status === 'pending').length;
  const done = g.orders.filter((o) => o.status === 'done').length;
  const plates = g.orders.reduce(
    (s, o) => s + (o.actualSheets ?? o.estimatedSheets ?? 0),
    0,
  );
  const pieces = g.orders.reduce((s, o) => s + totalPieces(o.shapes), 0);
  const initial = (g.name || '?').slice(0, 1).toUpperCase();
  const roleLabel = g.role.toUpperCase();

  return `
  <section class="worker-section">
    <div class="worker-header">
      <div class="worker-avatar">${esc(initial)}</div>
      <div class="worker-info">
        <div class="worker-name-row">
          <span class="worker-name">${esc(g.name)}</span>
          <span class="worker-role role-${esc(g.role)}">${esc(roleLabel)}</span>
        </div>
        <div class="worker-meta">
          ${g.orders.length} order${g.orders.length === 1 ? '' : 's'}
          · ${pending} pending
          · ${done} done
          · ${plates} sheets
          · ${pieces} pcs
        </div>
      </div>
    </div>
    <div class="orders-grid">
      ${g.orders.map(renderOrder).join('')}
    </div>
  </section>
  `;
}

function renderOrder(o: Order): string {
  const overrideUsed = o.actualSheets != null;
  const sheetsLabel = overrideUsed
    ? `${o.actualSheets} <span class="sheets-meta">(actual · est. ${o.estimatedSheets})</span>`
    : `${o.estimatedSheets} <span class="sheets-meta">(estimated)</span>`;
  const pieces = totalPieces(o.shapes);
  const area = totalAreaCm2(o.shapes);
  const areaSqM = (area / 10_000).toFixed(2);

  const dimRows = o.shapes
    .flatMap((shape, i) =>
      shape.dimensions.map(
        (d) => `
        <tr>
          <td>Shape ${i + 1}</td>
          <td>${esc(d.width)} × ${esc(d.height)} cm</td>
          <td class="num">×${esc(d.quantity)}</td>
        </tr>`,
      ),
    )
    .join('');

  return `
    <div class="order-row">
      <div class="order-header">
        <div class="order-title-block">
          <div class="order-name">${esc(o.name)}</div>
          <div class="order-time">
            ${esc(formatDateTime(o.createdAt))} · ${esc(o.thickness)} thickness
          </div>
        </div>
        <span class="status-pill status-${esc(o.status)}">
          ${o.status === 'done' ? 'Done' : 'In Queue'}
        </span>
      </div>

      <div class="order-meta">
        <span class="meta-item">
          <span class="meta-label">Plates</span>
          <span class="meta-value">${sheetsLabel}</span>
        </span>
        <span class="meta-item">
          <span class="meta-label">Shapes</span>
          <span class="meta-value">${o.shapes.length}</span>
        </span>
        <span class="meta-item">
          <span class="meta-label">Pieces</span>
          <span class="meta-value">${pieces}</span>
        </span>
        <span class="meta-item">
          <span class="meta-label">Area</span>
          <span class="meta-value">${areaSqM} m²</span>
        </span>
      </div>

      <table class="shapes-table">
        <thead>
          <tr>
            <th>Shape</th>
            <th>Dimensions</th>
            <th class="num">Qty</th>
          </tr>
        </thead>
        <tbody>${dimRows}</tbody>
      </table>

      ${
        o.notes
          ? `<div class="order-notes">
              <span class="notes-label">Notes</span>
              <span>${esc(o.notes)}</span>
            </div>`
          : ''
      }

      ${
        o.executionFiles && o.executionFiles.length > 0
          ? `<div class="files-list">
              <div class="files-label">Execution files (${o.executionFiles.length})</div>
              ${o.executionFiles
                .map(
                  (f) => `<div class="files-item">
                    <span class="files-bullet">▣</span>
                    <span class="files-name">${esc(f.name)}</span>
                    ${
                      f.size
                        ? `<span class="files-size">${esc(formatSize(f.size))}</span>`
                        : ''
                    }
                  </div>`,
                )
                .join('')}
            </div>`
          : ''
      }
    </div>
  `;
}

function formatDateTime(ts: number): string {
  return new Date(ts).toLocaleString(undefined, {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function esc(value: unknown): string {
  if (value === undefined || value === null) return '';
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const baseStyles = `
  @page { margin: 18mm 14mm; }
  * { box-sizing: border-box; }
  html, body {
    margin: 0;
    padding: 0;
    color: #1A1C20;
    background: #ffffff;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
    font-size: 12px;
    line-height: 1.5;
  }

  /* Brand bar */
  .brand-bar {
    background: #0E0F12;
    color: #F5F1EA;
    padding: 22px 26px;
    border-radius: 10px;
    margin-bottom: 22px;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    border-left: 6px solid #E07A2E;
  }
  .brand-mark {
    letter-spacing: 2px;
    font-size: 10px;
    color: #E07A2E;
    text-transform: uppercase;
    font-weight: 700;
  }
  .brand-title {
    font-size: 24px;
    font-weight: 700;
    margin-top: 4px;
    letter-spacing: -0.3px;
  }
  .brand-subtitle {
    font-size: 12px;
    color: #A9A39A;
    margin-top: 6px;
  }
  .brand-badge {
    background: rgba(224, 122, 46, 0.18);
    border: 1px solid #E07A2E;
    color: #E07A2E;
    padding: 6px 12px;
    border-radius: 999px;
    font-size: 10px;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1px;
  }

  /* Stats grid (table-based for PDF reliability) */
  .stats-grid {
    display: table;
    width: 100%;
    border-spacing: 8px;
    margin: 0 -8px 16px;
  }
  .stats-grid > .stat-card {
    display: table-cell;
    width: 25%;
    border: 1px solid #E5DDD2;
    border-radius: 8px;
    padding: 12px 14px;
    background: #FAF7F2;
    vertical-align: top;
  }
  .stat-label {
    font-size: 9px;
    text-transform: uppercase;
    color: #6B6760;
    letter-spacing: 1px;
    font-weight: 700;
  }
  .stat-value {
    font-size: 24px;
    font-weight: 700;
    color: #1A1C20;
    margin-top: 4px;
    line-height: 1.1;
  }
  .stat-unit {
    font-size: 10px;
    color: #A9A39A;
    margin-left: 4px;
    font-weight: 500;
  }
  .stat-card.accent { border-color: #E07A2E; background: #FFF5EB; }
  .stat-card.accent .stat-value { color: #B85F1F; }
  .stat-card.warning { border-color: #E0A33A; background: #FFF8E8; }
  .stat-card.warning .stat-value { color: #8E6308; }
  .stat-card.success { border-color: #5DB075; background: #EAF5ED; }
  .stat-card.success .stat-value { color: #2F7748; }

  .meta-row {
    margin: 4px 0 22px;
    color: #5A5A5A;
    font-size: 11px;
    padding: 10px 14px;
    background: #FAF7F2;
    border-radius: 6px;
    border-left: 3px solid #E4B65C;
  }
  .meta-row strong { color: #1A1C20; font-weight: 700; }

  /* Worker section */
  .worker-section {
    margin-bottom: 22px;
    page-break-inside: avoid;
  }
  .worker-header {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 12px 14px;
    background: #1A1C20;
    color: #F5F1EA;
    border-radius: 8px 8px 0 0;
  }
  .worker-avatar {
    width: 34px;
    height: 34px;
    border-radius: 17px;
    background: rgba(224, 122, 46, 0.2);
    border: 1px solid #E07A2E;
    color: #E07A2E;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: 700;
    font-size: 14px;
    flex-shrink: 0;
  }
  .worker-info { flex: 1; }
  .worker-name-row { display: flex; align-items: center; gap: 8px; }
  .worker-name { font-weight: 700; font-size: 15px; }
  .worker-role {
    padding: 2px 8px;
    border-radius: 12px;
    font-size: 9px;
    text-transform: uppercase;
    letter-spacing: 1px;
    font-weight: 700;
  }
  .role-internal { background: #0F1F2C; color: #5A9CC9; }
  .role-external { background: #1E102C; color: #B36BD9; }
  .role-manager { background: #3A1F10; color: #E07A2E; }
  .worker-meta {
    font-size: 10px;
    color: #A9A39A;
    margin-top: 3px;
  }

  /* Orders */
  .orders-grid {
    border: 1px solid #E5DDD2;
    border-top: none;
    border-radius: 0 0 8px 8px;
    overflow: hidden;
  }
  .order-row {
    padding: 12px 14px;
    border-bottom: 1px solid #EFE9DF;
    page-break-inside: avoid;
    background: #ffffff;
  }
  .order-row:last-child { border-bottom: none; }
  .order-header {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 10px;
    margin-bottom: 8px;
  }
  .order-title-block { flex: 1; }
  .order-name {
    font-weight: 700;
    font-size: 14px;
    color: #1A1C20;
  }
  .order-time {
    font-size: 10px;
    color: #6B6760;
    margin-top: 2px;
  }
  .status-pill {
    padding: 3px 10px;
    border-radius: 12px;
    font-size: 9px;
    text-transform: uppercase;
    letter-spacing: 1px;
    font-weight: 700;
    white-space: nowrap;
  }
  .status-pending { background: #FFF1D9; color: #B07A0E; border: 1px solid #E0A33A; }
  .status-done { background: #DBF0E0; color: #2F7748; border: 1px solid #5DB075; }

  .order-meta {
    display: flex;
    flex-wrap: wrap;
    gap: 14px;
    margin: 8px 0;
    padding: 8px 10px;
    background: #FAF7F2;
    border-radius: 6px;
    font-size: 11px;
  }
  .meta-item { display: flex; flex-direction: column; min-width: 80px; }
  .meta-label {
    font-size: 9px;
    color: #6B6760;
    text-transform: uppercase;
    letter-spacing: 0.8px;
    font-weight: 700;
  }
  .meta-value {
    color: #1A1C20;
    font-weight: 700;
    margin-top: 2px;
  }
  .sheets-meta {
    color: #6B6760;
    font-size: 9px;
    font-weight: 500;
    margin-left: 2px;
  }

  .shapes-table {
    margin-top: 6px;
    width: 100%;
    border-collapse: collapse;
    font-size: 11px;
  }
  .shapes-table th {
    text-align: left;
    padding: 5px 8px;
    background: #F5F1EA;
    color: #6B6760;
    text-transform: uppercase;
    font-size: 9px;
    letter-spacing: 1px;
    border-bottom: 1px solid #E5DDD2;
  }
  .shapes-table td {
    padding: 5px 8px;
    border-bottom: 1px solid #EFE9DF;
    color: #1A1C20;
  }
  .shapes-table tr:last-child td { border-bottom: none; }
  .shapes-table .num { text-align: right; font-weight: 700; }

  .order-notes {
    margin-top: 8px;
    padding: 8px 10px;
    background: #FFFAEC;
    border-left: 3px solid #E4B65C;
    font-size: 11px;
    color: #5A5A5A;
    border-radius: 0 4px 4px 0;
  }
  .notes-label {
    font-size: 9px;
    text-transform: uppercase;
    color: #B07A0E;
    font-weight: 700;
    letter-spacing: 1px;
    margin-right: 6px;
  }

  .files-list {
    margin-top: 8px;
    padding: 8px 10px;
    background: #FFF5EB;
    border-left: 3px solid #E07A2E;
    border-radius: 0 4px 4px 0;
  }
  .files-label {
    font-size: 9px;
    text-transform: uppercase;
    color: #B85F1F;
    font-weight: 700;
    letter-spacing: 1px;
    margin-bottom: 4px;
  }
  .files-item {
    font-size: 11px;
    color: #1A1C20;
    margin-top: 2px;
    display: flex;
    align-items: center;
    gap: 6px;
  }
  .files-bullet { color: #E07A2E; font-size: 12px; }
  .files-name { font-weight: 600; }
  .files-size { color: #6B6760; font-size: 10px; }

  /* Empty state */
  .empty-state {
    padding: 40px;
    text-align: center;
    border: 1px dashed #E5DDD2;
    border-radius: 8px;
    background: #FAF7F2;
  }
  .empty-title {
    font-size: 16px;
    font-weight: 700;
    color: #1A1C20;
  }
  .empty-sub {
    font-size: 12px;
    color: #6B6760;
    margin-top: 4px;
  }

  footer {
    margin-top: 28px;
    padding: 14px;
    border-top: 1px solid #E5DDD2;
    color: #6B6760;
    font-size: 10px;
    text-align: center;
    line-height: 1.6;
  }
  .footer-brand {
    color: #E07A2E;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 1px;
    font-size: 9px;
  }
`;
